Handling of configuration unified
securesign/sigstore-e2e pull request #10
Opened 2023-11-28 17:18 UTC by petrpinkas

Skip test if mandatory configuration is missing

2023-11-29 10:26 UTC, osmman commented on pkg/support/testSupport.go
> +
We should consolidate and use only one style of imports 
1. alphabetized imports (gofmt)
2. imports grouped stdlib, newline, external (goimports)

2023-11-29 10:29 UTC, bouskaJ commented on pkg/support/testSupport.go
> +
I will work on CI action to cover that.

2023-11-29 10:30 UTC, bouskaJ commented
@petrpinkas can you rebase? #9 was merged

2023-11-29 11:08 UTC, petrpinkas commented
@bouskaJ @osmman Rebased

2023-11-29 14:29 UTC, bouskaJ requested changes
Well done @petrpinkas. It's quite impressive for your first PR :thumbsup:

2023-11-29 14:29 UTC, bouskaJ commented on test/cosign/cosign_sign_verify_test.go
> +		cli    *client.Client
Can you rename to `dockerCli` or something self-explanatory, please?

2023-11-29 14:29 UTC, bouskaJ commented on test/cosign/cosign_sign_verify_test.go
> +		logrus.Debug("Mandatory configuration:")
Maybe I am loosing point of this message - it ends with `:` with no details. If following lines are composed in the `CheckApiConfigValues` It would make more sense to make it part of `CheckApiConfigValues` function

2023-11-29 14:29 UTC, bouskaJ commented on test/tekton/gitsign_test.go
> +		GithubToken    = api.GetValueFor(api.GithubToken)
I am thinking about skipping the `viper` loading in the test specific vars and use `support.GetEnvOrDefault("TEST_GITHUB_USER", "ignore")` just like before.

It's more readable - a newbie would not need to search on how to provide values. The Viper framework is able to load from config files - that is the reason why it was introduced. Maybe we will store the product specific values in config files but it does not make too much sense for API tokens etc IMHO.

2023-11-30 17:52 UTC, petrpinkas commented on test/tekton/gitsign_test.go
> +		GithubToken    = api.GetValueFor(api.GithubToken)
We will let configuration on one place and hint will be added when the configuration value is missing.

2023-12-01 08:04 UTC, bouskaJ approved these changes
LGTM

2023-12-01 08:04 UTC, merged