[SECURESIGN-1279] Extend e2e scenarios by tuftool
securesign/sigstore-e2e pull request #35
Opened 2024-10-07 16:19 UTC by kdacosta0

`make test-tuf-repo`

- will delete `trusted-artifact-signer` namespace 
- deploy securesign with self-managed tuf repository (via `tuftool` cli binary)
- load variables and run tests

2024-10-08 14:27 UTC, petrpinkas requested changes
Does not work with CLI_STRATEGY:
`CLI_STRATEGY=openshift go test -v ./test/manual_tuf_repo --ginkgo.v`

```
t=2024-10-08T16:24:36+02:00 l=info m=Downloading cosign from https://cli-server-trusted-artifact-signer.apps.ci-ln-srctz8b-76ef8.aws-2.ci.openshift.org/clients/darwin/cosign-arm64.gz
panic: bad status: 503 Service Unavailable

goroutine 38 [running]:
github.com/securesign/sigstore-e2e/pkg/support.DownloadAndUnzip.func1()
	/Users/ppinkas/own/redhat/grepos/securesign/sigstore-e2e/pkg/support/testSupport.go:70 +0x98
created by github.com/securesign/sigstore-e2e/pkg/support.DownloadAndUnzip in goroutine 66
	/Users/ppinkas/own/redhat/grepos/securesign/sigstore-e2e/pkg/support/testSupport.go:67 +0x134
FAIL	github.com/securesign/sigstore-e2e/test/manual_tuf_repo	3.597s
```

2024-10-08 14:34 UTC, kdacosta0 commented
> Does not work with CLI_STRATEGY: `CLI_STRATEGY=openshift go test -v ./test/manual_tuf_repo --ginkgo.v`
> 
> ```
> t=2024-10-08T16:24:36+02:00 l=info m=Downloading cosign from https://cli-server-trusted-artifact-signer.apps.ci-ln-srctz8b-76ef8.aws-2.ci.openshift.org/clients/darwin/cosign-arm64.gz
> panic: bad status: 503 Service Unavailable
> 
> goroutine 38 [running]:
> github.com/securesign/sigstore-e2e/pkg/support.DownloadAndUnzip.func1()
> 	/Users/ppinkas/own/redhat/grepos/securesign/sigstore-e2e/pkg/support/testSupport.go:70 +0x98
> created by github.com/securesign/sigstore-e2e/pkg/support.DownloadAndUnzip in goroutine 66
> 	/Users/ppinkas/own/redhat/grepos/securesign/sigstore-e2e/pkg/support/testSupport.go:67 +0x134
> FAIL	github.com/securesign/sigstore-e2e/test/manual_tuf_repo	3.597s
> ```

yes, when I delete the `trusted-artifact-signer` namespace it will remove the cli-server, and it wont recreate it

to fix it i would probably need to remove all resources except the cli-server, should i try that?

2024-10-08 14:38 UTC, petrpinkas commented
If I understand it right, we just need to download tuf tool from op same as any other binary - cosign, gitsign. I have trusted-artifact-signer running, but it still does not work.

2024-10-08 14:42 UTC, petrpinkas commented
no ... aha, I didn't know it does not work this way ... TAS is installed in different namespace

2024-10-08 14:48 UTC, kdacosta0 commented
but you raised valid issue, because exactly this type of error will happen after you try to run another test with CLI_STRATEGY=openshift, after the manual_tuf_repo

tomorrow I can try to find out how the cli-server pod is created, and itegrate it into the test

2024-10-08 14:51 UTC, petrpinkas commented
I think we need to discuss it, not sure, what it does now, but it broke all other tests. I have a TAS installed in ppinkas-tas namespace and it worked. Now there is new TAS installed in trusted-artifact-signer namespace and no test is working any more with CLI_STRATEGY=openshift ...

2024-10-09 07:47 UTC, kdacosta0 commented
@petrpinkas I changed namespace to `tuf-repo-test` where securesign is deployed with the self-managed tuf repository. 

do I leave it like this where clean namespace `tuf-repo-test` will be created each test, or do I create new namespace with unique ID each time?

2024-11-12 12:07 UTC, petrpinkas commented
Please, no targets folder and files in that part of a commit. Are those files necessary?

2024-11-12 12:12 UTC, petrpinkas commented
If I remember right, we don't even need to communicate with a cluster. We just need to verify, that manually created structure is valid and has all the expected folders/files.

2024-11-14 12:47 UTC, petrpinkas commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +				validSuffix := false
This is a wrong logic - if for one file it will be true, it will never fail. I added test.pub to targetSuffixes and the test did not fail.

2024-11-14 12:47 UTC, petrpinkas commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +	Expect(expectedDirs).To(BeEmpty(), fmt.Sprintf("missing directories: %v", expectedDirs))
We need some better error message - what directory / files are missing and where. Now I get
```
  [FAILED] missing directories: map[test-dir:true]
  Expected
      <map[string]bool | len:1>: {"test-dir": true}
  to be empty
```
Same for unexpected directories/files:
```
  [FAILED] unexpected directory: tuf-test
  Expected
      <bool>: false
  to be true
```

2024-11-14 14:38 UTC, kdacosta0 commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +const timestampExpiration string = "in 10 days"
https://github.com/securesign/sigstore-e2e/blob/manual_tuf_repo/test/tuftool/tuftool_manual_tuf_repo_test.go#L29

```
const expirationWeeks52 string = "in 52 weeks"
const expirationDays10 string = "in 10 days"
```

2024-11-14 14:39 UTC, kdacosta0 commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +	Describe("Setup TUF repository via tuftool", func() {
https://github.com/securesign/sigstore-e2e/blob/manual_tuf_repo/test/tuftool/tuftool_manual_tuf_repo_test.go#L57

```
It("should setup repository via tuftool", func() {
             setupManualTufRepo(tuftool)
})

It("should verify workdir structure", func() {
              verifyWorkdirStructure(workdir)
})
```

2024-11-14 14:43 UTC, kdacosta0 commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +	Expect(expectedDirs).To(BeEmpty(), fmt.Sprintf("missing directories: %v", expectedDirs))
https://github.com/securesign/sigstore-e2e/blob/manual_tuf_repo/test/tuftool/tuftool_manual_tuf_repo_test.go#L266

```
[FAILED] missing files: [/var/folders/_l/bdjns3gn53z_dcglz5dhgtj80000gn/T/trustroot_example4264623185/tuf-repo/2.targets.json]
  Expected
      <[]string | len:1, cap:1>: [
          "/var/folders/_l/bdjns3gn53z_dcglz5dhgtj80000gn/T/trustroot_example4264623185/tuf-repo/2.targets.json",
      ]
  to be empty
```

https://github.com/securesign/sigstore-e2e/blob/manual_tuf_repo/test/tuftool/tuftool_manual_tuf_repo_test.go#L243
```
[FAILED] unexpected file: /var/folders/_l/bdjns3gn53z_dcglz5dhgtj80000gn/T/trustroot_example4260208089/test.pub
  Expected
      <bool>: false
  to be true
```

2024-11-14 15:15 UTC, kdacosta0 commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +				validSuffix := false
oh I think I see what you mean now. The test doesn't currently check if there are any missing files with the required suffixes. I’ve made the necessary adjustments to ensure the test properly verifies that there is one file of each required suffixes (and at least one `.trusted_root.json`, because these can be more) are present in the `tuf-repo/targets/` directory. If any of the specified files are missing, the test will now fail as expected. 

https://github.com/securesign/sigstore-e2e/blob/manual_tuf_repo/test/tuftool/tuftool_manual_tuf_repo_test.go#L275

2024-11-15 11:33 UTC, petrpinkas commented on test/tuftool/tuftool_manual_tuf_repo_test.go
> +				validSuffix := false
Now works fine, thank you!

2024-11-15 11:33 UTC, petrpinkas approved these changes

2024-11-15 11:34 UTC, merged